"""
06_combine_and_prefilter.py - Multi-Gene Screening Combiner & Prefilter
========================================================================
Merges parallelized screening chunk outputs, applies fast physicochemical 
property filtering (MW, LogP), eliminates known active controls, 
and enforces exact prediction score thresholds.

"""

import os
import sys
import pandas as pd
from rdkit import Chem
from rdkit.Chem import Descriptors

# ============================================================================
# MLOps CONFIGURATION & PATH MANAGEMENT
# ============================================================================

# Target gene can be passed from terminal environment or defaults to CTNNB1
GENE_NAME = os.environ.get("TARGET_GENE", "CTNNB1")
SCORE_THRESHOLD = 0.80

# Navigate relative to script positioning (scripts/ to central data/)
BASE_DATA_DIR = "../data"
ACTIVE_FILE = os.path.join(BASE_DATA_DIR, "03_fingerprints", f"{GENE_NAME}_active_curated.csv")

# Dynamic screening folder detection based on the latest generated predictions
SCREENING_ROOT = f"../screening/{GENE_NAME}"

if not os.path.exists(SCREENING_ROOT):
    print(f"❌ ERROR: Screening root directory not found for {GENE_NAME}: {SCREENING_ROOT}")
    sys.exit(1)

# Auto-detect latest experiment folder generated by 06_final_screening.py
latest_pred_dir = sorted([d for d in os.listdir(SCREENING_ROOT) if d.startswith("predictions_")])[-1]
WORK_DIR = os.path.join(SCREENING_ROOT, latest_pred_dir)

print(f"🧬 Active Gene Pipeline : {GENE_NAME}")
print(f"📂 Detected Work Dir    : {WORK_DIR}")
print(f"🎯 Score Threshold      : ≥{SCORE_THRESHOLD}")

# ============================================================================
# FILTERING UTILITIES
# ============================================================================

def fast_prefilter(smiles):
    """Fast physicochemical filters: MW and LogP constraints"""
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return False
        
        mw = Descriptors.MolWt(mol)
        if mw < 200 or mw > 600:
            return False
        
        logp = Descriptors.MolLogP(mol)
        if logp < -0.5 or logp > 5.5:
            return False
        
        return True
    except:
        return False

# ============================================================================
# MAIN PIPELINE EXECUTION
# ============================================================================

def run_step1():
    print(f"\n{'='*80}")
    print(f"🔬 {GENE_NAME} ({latest_pred_dir.upper()}) - MERGING & PREFILTERING PIPELINE")
    print("="*80)
    
    # Switch execution contexts directly into the dynamic outputs folder
    os.chdir(WORK_DIR)
    
    print("\n=== STAGE 1: Chunk File Aggregation ===")
    data_frames = []
    chunk_files = [f for f in os.listdir(".") if f.startswith("filtered_chunk_") and f.endswith(".csv")]
    
    if not chunk_files:
        print("❌ ERROR: No filtered_chunk_*.csv files detected in this context!")
        print("   Verify that 06_final_screening.py ran successfully and generated hits.")
        return
    
    print(f"📊 Identified {len(chunk_files)} chunk outputs. Compiling...")
    
    for file_name in sorted(chunk_files):
        df = pd.read_csv(file_name)
        data_frames.append(df)
        print(f"  ✓ Packed {file_name} : {len(df):,} structures loaded.")
    
    combined_df = pd.concat(data_frames, ignore_index=True)
    initial_count = len(combined_df)
    print(f"\n✅ Total Raw Unified Pools: {initial_count:,} molecules.")
    
    print("\n=== STAGE 2: Fast Molecular Descriptors Filter (MW, LogP) ===")
    print("⏳ Evaluating Rule-of-Thumb space (200 <= MW <= 600 | -0.5 <= LogP <= 5.5)...")
    combined_df['fast_filter_passed'] = combined_df['Canonical_SMILES'].apply(fast_prefilter)
    combined_df = combined_df[combined_df['fast_filter_passed'] == True].drop('fast_filter_passed', axis=1)
    after_fast_filter = len(combined_df)
    print(f"✅ Post Descriptor Filtration: {after_fast_filter:,} structures remain ({after_fast_filter/initial_count*100:.2f}%)")
    
    print("\n=== STAGE 3: Extraction of Known Positive Controls ===")
    if os.path.exists(ACTIVE_FILE):
        active_df = pd.read_csv(ACTIVE_FILE)
        before_active_removal = len(combined_df)
        
        # Cross-reference known active compounds to isolate novel chemical space
        combined_df = combined_df[~combined_df['CID'].isin(active_df['PUBCHEM_CID'])]
        after_active_removal = len(combined_df)
        removed = before_active_removal - after_active_removal
        print(f"✅ Successfully removed {removed:,} known active control structures.")
        print(f"   Novel space remaining: {after_active_removal:,} structures.")
    else:
        print(f"⚠️  WARNING: Active baseline file missing at: {ACTIVE_FILE}. Skipping elimination.")
        after_active_removal = len(combined_df)
    
    print("\n=== STAGE 4: Rigid Model Threshold Enforcement ===")
    filtered_df = combined_df[combined_df['prediction_score'] >= SCORE_THRESHOLD]
    after_score = len(filtered_df)
    print(f"📊 Retained above confidence barrier (≥{SCORE_THRESHOLD}): {after_score:,} hits ({after_score/after_active_removal*100:.2f}%)")
    
    print("\n=== STAGE 5: Scoring Layout Sorting ===")
    filtered_df = filtered_df.sort_values(by="prediction_score", ascending=False)
    print(f"✅ Feature arrays sorted by probability parameters.")
    print(f"   🏆 Max Active Boundary Score: {filtered_df['prediction_score'].max():.4f}")
    print(f"   📉 Min Active Boundary Score: {filtered_df['prediction_score'].min():.4f}")
    print(f"   📊 Pool Mean Affinity Score : {filtered_df['prediction_score'].mean():.4f}")
    
    # Construct completely dynamic output names based on target configurations
    exp_suffix = latest_pred_dir.split("_")[-1]  # Extracts 'exp06' or 'exp07'
    output_file = f"{GENE_NAME.lower()}_{exp_suffix}_prefiltered.csv"
    filtered_df.to_csv(output_file, index=False)
    
    print(f"\n{'='*80}")
    print(f"🎯 PIPELINE STEP 1 COMPLETED SUCCESSFULLY FOR {GENE_NAME}")
    print(f"{'='*80}")
    print(f"📥 Input Cumulative Pool : {initial_count:,} structures.")
    print(f"📤 Purified Output Pool   : {len(filtered_df):,} structures.")
    print(f"📉 Space Size Reduction  : {(1 - len(filtered_df)/initial_count)*100:.2f}%")
    print(f"💾 Saved Artifact Destination: {os.path.join(WORK_DIR, output_file)}")
    print(f"{'='*80}\n")

if __name__ == "__main__":
    run_step1()