"""
07_toxicity_and_grouping.py - Multi-Gene Chemical Refinery Pipeline
===================================================================
Applies advanced medicinal chemistry filters (PAINS/Brenk toxicophores, 
Lipinski Rule of 5, Veber parameters) and executes structural diversity 
clustering using Tanimoto distance to select the final lead candidates.

Date: 2026-06-22
"""

import os
import sys
import time
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import Descriptors, AllChem, DataStructs
from rdkit.Chem.FilterCatalog import FilterCatalog, FilterCatalogParams

# ============================================================================
# Target gene can be passed from terminal environment or defaults to CTNNB1
GENE_NAME = os.environ.get("TARGET_GENE", "CTNNB1")
TARGET_MOLECULES = 1000
TANIMOTO_THRESHOLD = 0.6
MAX_LIPINSKI_VIOLATIONS = 2

# Navigate relative to script positioning (scripts/ to screening/)
SCREENING_ROOT = f"../screening/{GENE_NAME}"

if not os.path.exists(SCREENING_ROOT):
    print(f" ERROR: Screening root directory not found for {GENE_NAME}: {SCREENING_ROOT}")
    sys.exit(1)

# Auto-detect latest experiment folder generated by 06_final_screening.py
latest_pred_dir = sorted([d for d in os.listdir(SCREENING_ROOT) if d.startswith("predictions_")])[-1]
WORK_DIR = os.path.join(SCREENING_ROOT, latest_pred_dir)

# Construct completely dynamic input filename matching 06_combine_and_prefilter.py output template
exp_suffix = latest_pred_dir.split("_")[-1]  # Extracts 'exp06' or 'exp07'
INPUT_FILE = f"{GENE_NAME.lower()}_{exp_suffix}_prefiltered.csv"

print(f" Active Gene Pipeline : {GENE_NAME}")
print(f" Detected Work Dir    : {WORK_DIR}")
print(f" Target Input File    : {INPUT_FILE}")

class FilteringStats:
    """Tracks and logs filtration step reductions dynamically"""
    def __init__(self):
        self.stages = []
    
    def add_stage(self, stage_name, count, percentage, avg_score=None, notes=""):
        self.stages.append({
            'stage': stage_name,
            'count': count,
            'percentage': percentage,
            'avg_score': avg_score,
            'notes': notes
        })
    
    def save_report(self, filename):
        with open(filename, 'w') as f:
            f.write("="*80 + "\n")
            f.write(f"{GENE_NAME} {exp_suffix.upper()} REFINERY & FILTRATION REPORT\n")
            f.write("="*80 + "\n\n")
            
            for i, stage in enumerate(self.stages, 1):
                f.write(f"AŞAMA {i}: {stage['stage']}\n")
                f.write(f"  Kalan Molekül: {stage['count']:,}\n")
                f.write(f"  Yüzde: {stage['percentage']:.2f}%\n")
                if stage['avg_score']:
                    f.write(f"  Ortalama Skor: {stage['avg_score']:.4f}\n")
                if stage['notes']:
                    f.write(f"  Not: {stage['notes']}\n")
                f.write("\n")
            
            f.write("="*80 + "\n")
            f.write(f"FİNAL SONUÇ: {self.stages[-1]['count']:,} Molekül (Docking Ready)\n")
            f.write("="*80 + "\n")

# ============================================================================
# MEDICINAL CHEMISTRY FILTERS
# ============================================================================

def check_pains_brenk(smiles, catalog):
    """PAINS and Brenk toxicophore filtration"""
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return False
        return not catalog.HasMatch(mol)
    except:
        return False

def calculate_lipinski_violations(smiles):
    """Calculates Lipinski Rule of 5 violations counts"""
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return 999
        
        violations = 0
        if Descriptors.MolWt(mol) > 500: violations += 1
        if Descriptors.MolLogP(mol) > 5: violations += 1
        if Descriptors.NumHDonors(mol) > 5: violations += 1
        if Descriptors.NumHAcceptors(mol) > 10: violations += 1
        return violations
    except:
        return 999

def check_detailed_druglikeness(smiles):
    """Detailed druglikeness filters (Veber constraints + structural quality)"""
    try:
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return False
        
        tpsa = Descriptors.TPSA(mol)
        if tpsa < 60 or tpsa > 140: return False
        
        n_rot = Descriptors.NumRotatableBonds(mol)
        if n_rot > 15: return False
        
        fsp3 = Descriptors.FractionCSP3(mol)
        if fsp3 < 0.2: return False
        
        aromatic_rings = Descriptors.NumAromaticRings(mol)
        if aromatic_rings > 4: return False
        
        formal_charge = Chem.rdmolops.GetFormalCharge(mol)
        if abs(formal_charge) > 1: return False
        
        return True
    except:
        return False

# ============================================================================
# DIVERSITY CLUSTERING (TANIMOTO MINING ENGINE)
# ============================================================================

def diversity_clustering(df, target_count, similarity_threshold):
    print(f"\n🧬 Diversity Clustering Engine Initialized...")
    print(f"   Target Limit: {target_count} Leaders | Similarity Ceiling: Tanimoto {similarity_threshold}")
    
    df_sorted = df.sort_values(by="prediction_score", ascending=False).reset_index(drop=True)
    
    print(" Computing Morgan fingerprints (Radius=2, 2048-bit)...")
    mols = []
    valid_indices = []
    for idx, smiles in enumerate(df_sorted['Canonical_SMILES']):
        mol = Chem.MolFromSmiles(smiles)
        if mol is not None:
            mols.append(mol)
            valid_indices.append(idx)
    
    df_sorted = df_sorted.iloc[valid_indices].reset_index(drop=True)
    fps = [AllChem.GetMorganFingerprintAsBitVect(m, 2, nBits=2048) for m in mols]
    
    print(f" {len(fps):,} structures converted to bit arrays successfully.")
    
    selected_indices = []
    remaining = list(range(len(df_sorted)))
    cluster_info = []
    
    print(" Executing non-redundant scaffold clustering isolation...")
    
    while len(selected_indices) < target_count and remaining:
        current = remaining.pop(0)
        selected_indices.append(current)
        
        group_members = [current]
        to_remove = []
        
        for i in remaining:
            sim = DataStructs.TanimotoSimilarity(fps[current], fps[i])
            if sim >= similarity_threshold:
                group_members.append(i)
                to_remove.append(i)
        
        for r in to_remove:
            remaining.remove(r)
        
        members_df = df_sorted.iloc[group_members]
        cluster_info.append({
            "Cluster_ID": len(selected_indices),
            "Representative_CID": df_sorted.iloc[current]['CID'],
            "Representative_Score": df_sorted.iloc[current]['prediction_score'],
            "Cluster_Size": len(group_members),
            "Member_CIDs": members_df['CID'].tolist(),
            "Avg_Similarity": np.mean([DataStructs.TanimotoSimilarity(fps[current], fps[i]) for i in group_members])
        })
        
        if len(selected_indices) % 100 == 0:
            print(f"   ✓ Selected {len(selected_indices)} unique cluster heads...")
    
    print(f" Structural mining finished: {len(selected_indices)} diverse leads selected.")
    
    final_df = df_sorted.iloc[selected_indices].copy()
    cluster_df = pd.DataFrame(cluster_info)
    
    return final_df, cluster_df

# ============================================================================
# MAIN PIPELINE EXECUTION
# ============================================================================

def run_step2():
    # Context switch execution domain into the dynamic predictions path
    os.chdir(WORK_DIR)
    
    print("="*80)
    print(f" {GENE_NAME} ({exp_suffix.upper()}) - BIO-CHEMICAL REFINERY & LEAD SELECTION")
    print("="*80)
    
    stats = FilteringStats()
    
    try:
        df = pd.read_csv(INPUT_FILE)
        initial_count = len(df)
        print(f"\n Loading prefitered pool: {INPUT_FILE}")
        print(f" Starting size: {initial_count:,} molecules")
        stats.add_stage("Başlangıç (Step 1 çıktısı)", initial_count, 100.0, 
                       df['prediction_score'].mean(), "Hızlı filtreler uygulanmış")
    except FileNotFoundError:
        print(f" CRITICAL ERROR: compiled pool target file '{INPUT_FILE}' not found.")
        print("   Please execute 06_combine_and_prefilter.py before running this refinery.")
        return
    
    print("\n" + "="*80)
    print("AŞAMA 1: PAINS VE BRENK TOKSİSİTE SEÇİMLERİ")
    print("="*80)
    
    params = FilterCatalogParams()
    params.AddCatalog(FilterCatalogParams.FilterCatalogs.PAINS)
    params.AddCatalog(FilterCatalogParams.FilterCatalogs.BRENK)
    catalog = FilterCatalog(params)
    
    print(" Scanning structures for toxicophoric patterns...")
    start_time = time.time()
    df['pains_passed'] = df['Canonical_SMILES'].apply(lambda x: check_pains_brenk(x, catalog))
    df = df[df['pains_passed'] == True].drop('pains_passed', axis=1)
    elapsed = time.time() - start_time
    
    after_pains = len(df)
    print(f" Toxicophore elimination finished ({elapsed:.1f}s)")
    print(f"   Safe structures remaining: {after_pains:,} ({after_pains/initial_count*100:.1f}%)")
    stats.add_stage("PAINS/Brenk Filtresi", after_pains, after_pains/initial_count*100,
                   df['prediction_score'].mean(), "Problematik yapılar elendi")
    
    print("\n" + "="*80)
    print("AŞAMA 2: HESAPLAMA OPTİMİZASYONU SINIRLAMASI (Top 50,000)")
    print("="*80)
    
    if len(df) > 50000:
        df = df.nlargest(50000, 'prediction_score')
        print(f" Truncated pool to top 50,000 structures to optimize clustering runtime.")
        print(f"   Probability Range: {df['prediction_score'].min():.4f} - {df['prediction_score'].max():.4f}")
    else:
        print(f"  Pool size safely under runtime thresholds ({len(df):,})")
    
    after_top_selection = len(df)
    stats.add_stage("Top 50K Seçimi", after_top_selection, after_top_selection/initial_count*100,
                   df['prediction_score'].mean(), "Hesaplama optimizasyonu")
    
    print("\n" + "="*80)
    print("AŞAMA 3: LIPINSKI RULE OF 5 VALIDATION (Max 2 Violations)")
    print("="*80)
    
    print(" Evaluating drug-likeness boundary violations...")
    df['lipinski_violations'] = df['Canonical_SMILES'].apply(calculate_lipinski_violations)
    df = df[df['lipinski_violations'] <= MAX_LIPINSKI_VIOLATIONS]
    
    after_lipinski = len(df)
    print(f"✅ Lipinski Ro5 compliance verified.")
    print(f"   Compliant structures remaining: {after_lipinski:,} ({after_lipinski/initial_count*100:.1f}%)")
    
    violation_counts = df['lipinski_violations'].value_counts().sort_index()
    for v, count in violation_counts.items():
        print(f"   {v} ihlal: {count:,} molekül")
    
    stats.add_stage("Lipinski Filtresi (≤2 ihlal)", after_lipinski, after_lipinski/initial_count*100,
                   df['prediction_score'].mean(), f"İhlal dağılımı kaydedildi")
    
    print("\n" + "="*80)
    print("AŞAMA 4: ADANCED DRUGLIKENESS CRITERIA (Veber Parameters)")
    print("="*80)
    
    print("⏳ Scanning TPSA, FractionCSP3, and rotatable bonds properties...")
    df['detailed_druglike'] = df['Canonical_SMILES'].apply(check_detailed_druglikeness)
    df = df[df['detailed_druglike'] == True].drop('detailed_druglike', axis=1)
    
    after_detailed = len(df)
    print(f"✅ Rigid parameter filters completed.")
    print(f"   Purified structures remaining: {after_detailed:,} ({after_detailed/initial_count*100:.1f}%)")
    stats.add_stage("Veber + Yapısal Kalite", after_detailed, after_detailed/initial_count*100,
                   df['prediction_score'].mean(), "TPSA, Fsp3, aromatik halka kontrolleri")
    
    print("\n" + "="*80)
    print("AŞAMA 5: NON-REDUNDANT STRUCTURAL DIVERSITY MINING")
    print("="*80)
    
    final_df, cluster_df = diversity_clustering(df, TARGET_MOLECULES, TANIMOTO_THRESHOLD)
    final_count = len(final_df)
    
    stats.add_stage("Diversity Clustering", final_count, final_count/initial_count*100,
                   final_df['prediction_score'].mean(), 
                   f"Tanimoto {TANIMOTO_THRESHOLD}, {len(cluster_df)} cluster")
    
    print("\n" + "="*80)
    print("EXPORTING ARTIFACTS TO EXPERIMENT DIRECTORY")
    print("="*80)
    
    # Construct completely dynamic output destinations
    final_output = f"{GENE_NAME.lower()}_{exp_suffix}_final_1000.csv"
    cluster_output = f"{GENE_NAME.lower()}_{exp_suffix}_clusters.csv"
    report_output = f"{GENE_NAME.lower()}_{exp_suffix}_filtering_report.txt"
    
    final_df_clean = final_df.drop('lipinski_violations', axis=1, errors='ignore')
    final_df_clean.to_csv(final_output, index=False)
    print(f"✅ Lead file exported: {final_output} ({len(final_df_clean):,} unique compounds)")
    
    cluster_df.to_csv(cluster_output, index=False)
    print(f"✅ Cluster metadata exported: {cluster_output} ({len(cluster_df):,} groups mapped)")
    
    stats.save_report(report_output)
    print(f"✅ Rapor dosyası dışa aktarıldı: {report_output}")
    
    print("\n" + "="*80)
    print("🎯 REFINERY PIPELINE TERMINATED - FINAL METRICS SUMMARY")
    print("="*80)
    print(f"📥 Input Cumulative Pool      : {initial_count:,} compounds.")
    print(f"📤 Purified Output Pool        : {final_count:,} lead drug candidates.")
    print(f"📉 Cumulative Space Reduction  : {(1 - final_count/initial_count)*100:.2f}%")
    print(f"⭐ Mean Active Affinity Score  : {final_df['prediction_score'].mean():.4f}")
    print(f"🏆 Max Active Affinity Score  : {final_df['prediction_score'].max():.4f}")
    print(f"📊 Extracted Diverse Clusters : {len(cluster_df):,}")
    print(f"🧬 Average Group Density Size : {cluster_df['Cluster_Size'].mean():.1f} structures/cluster")
    print("="*80)
    print(f"\n✅ All structures are verified and ready for molecular docking tests!")
    print(f"   Destination File: {os.path.join(WORK_DIR, final_output)}")

if __name__ == "__main__":
    run_step2()